Repository SysWin1/OneStepOneStamp, pull requests merged in 2024-08, with the labels that each got.

#50 47 [JavaFX] 유저 메인 페이지
  build.gradle
  src/main/java/module-info.java
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDAO.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyFormViewController.java
  src/main/java/org/example/onesteponestamp/javafx/UserMainViewController.java
  src/main/resources/org/example/onesteponestamp/AutoApplyFormView.fxml
  src/main/resources/org/example/onesteponestamp/UserMainContentView.fxml
  src/main/resources/org/example/onesteponestamp/UserMainView.fxml
  src/main/resources/org/example/onesteponestamp/css/AutoApplyForm.css
  src/main/resources/org/example/onesteponestamp/css/UserMain.css
  src/main/resources/org/example/onesteponestamp/images/gate.png
  src/main/resources/org/example/onesteponestamp/images/github.png
  src/main/resources/org/example/onesteponestamp/images/logo.png
Labels: 💫feature, ⭐sytle, 🔮 refactor, ✨chore, ❌ remove

#55 관리자 페이지 FXML 적용하였습니다.
  src/main/java/org/example/onesteponestamp/admin/LoginController.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationDTO.java
  src/main/java/org/example/onesteponestamp/javafx/AdminLoginPage.java
  src/main/java/org/example/onesteponestamp/javafx/AdminMain.java
  src/main/java/org/example/onesteponestamp/javafx/AdminMainController.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyForm.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListController.java
  src/main/java/org/example/onesteponestamp/javafx/ImmigrationListController.java
  src/main/java/org/example/onesteponestamp/javafx/ImmigrationListForm.java
  src/main/java/org/example/onesteponestamp/javafx/SelectionMain.java
  src/main/java/org/example/onesteponestamp/javafx/UserMain.java
  src/main/java/org/example/onesteponestamp/javafx/UserMainViewController.java
  src/main/resources/org/example/onesteponestamp/css/ImmigrationList.css
  src/main/resources/org/example/onesteponestamp/css/autoApplyList.css
  src/main/resources/org/example/onesteponestamp/javafx/AdminLogIn.fxml
  src/main/resources/org/example/onesteponestamp/javafx/AdminMain.fxml
  src/main/resources/org/example/onesteponestamp/javafx/AutoApplyList.fxml
  src/main/resources/org/example/onesteponestamp/javafx/ImmigrationList.fxml
Labels: ⭐sytle, ❌ remove, 😶‍🌫️ rename

#58 Table에 관리자용 "자동 출입국 신청서" 목록 연결
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListController.java
  src/main/resources/org/example/onesteponestamp/javafx/AutoApplyList.fxml
Labels: 🔮 refactor, 💣 hotifx

#59 외국인 페이지 Refactor 및 CSS 적용
  src/main/java/org/example/onesteponestamp/javafx/AdminMainController.java
  src/main/java/org/example/onesteponestamp/javafx/ForeignerFormController.java
  src/main/resources/org/example/onesteponestamp/Foreigner-view.fxml
  src/main/resources/org/example/onesteponestamp/css/foreignerStyle.css
  src/main/resources/org/example/onesteponestamp/css/ideal.css
  src/main/resources/org/example/onesteponestamp/css/style.css
  src/main/resources/org/example/onesteponestamp/javafx/foreignerView.fxml
Labels: ⭐sytle, 🔮 refactor

#60 폰트 및 배경 스타일 적용
  src/main/java/org/example/onesteponestamp/admin/LoginController.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationDAO.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListController.java
  src/main/java/org/example/onesteponestamp/javafx/ImmigrationListController.java
  src/main/resources/org/example/onesteponestamp/css/ImmigrationList.css
  src/main/resources/org/example/onesteponestamp/css/adminLogin.css
  src/main/resources/org/example/onesteponestamp/css/adminMain.css
  src/main/resources/org/example/onesteponestamp/css/alert.css
  src/main/resources/org/example/onesteponestamp/css/autoApplyList.css
  src/main/resources/org/example/onesteponestamp/css/immigrationListStyles.css
  src/main/resources/org/example/onesteponestamp/fonts/DoHyeon-Regular.ttf
  src/main/resources/org/example/onesteponestamp/images/logo.png
  src/main/resources/org/example/onesteponestamp/javafx/AdminMain.fxml
  src/main/resources/org/example/onesteponestamp/javafx/AutoApplyList.fxml
  src/main/resources/org/example/onesteponestamp/javafx/ImmigrationList.fxml
Labels: ⭐sytle

#64 유저 - 자동 출입국 신청서 목록 조회
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/admin/LoginController.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyAdminController.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDAO.java
  src/main/java/org/example/onesteponestamp/javafx/AdminLogInController.java
  src/main/java/org/example/onesteponestamp/javafx/AdminMainController.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyFormViewController.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListController.java
  src/main/java/org/example/onesteponestamp/javafx/UserAutoApplyListController.java
  src/main/java/org/example/onesteponestamp/javafx/UserMainViewController.java
  src/main/resources/org/example/onesteponestamp/Foreigner-view.fxml
  src/main/resources/org/example/onesteponestamp/css/AutoApplyForm.css
  src/main/resources/org/example/onesteponestamp/css/UserAutoApplyList.css
  src/main/resources/org/example/onesteponestamp/css/UserMain.css
  src/main/resources/org/example/onesteponestamp/fxml/AdminLogIn.fxml
  src/main/resources/org/example/onesteponestamp/fxml/AdminMain.fxml
  src/main/resources/org/example/onesteponestamp/fxml/AutoApplyFormView.fxml
  src/main/resources/org/example/onesteponestamp/fxml/AutoApplyList.fxml
  src/main/resources/org/example/onesteponestamp/fxml/ImmigrationList.fxml
  src/main/resources/org/example/onesteponestamp/fxml/UserAutoApplyListView.fxml
  src/main/resources/org/example/onesteponestamp/fxml/UserMainContentView.fxml
  src/main/resources/org/example/onesteponestamp/fxml/UserMainView.fxml
  src/main/resources/org/example/onesteponestamp/fxml/foreignerView.fxml
  src/main/resources/org/example/onesteponestamp/hello-view.fxml
  src/main/resources/org/example/onesteponestamp/images/logo.jpeg
  src/main/resources/org/example/onesteponestamp/javafx/AdminMain.fxml
  src/main/resources/org/example/onesteponestamp/javafx/AutoApplyFormView.fxml
  src/main/resources/org/example/onesteponestamp/javafx/UserMainContentView.fxml
Labels: ⭐sytle, 🔮 refactor, ✨chore, ❌ remove

#66 어드민 페이지 CSS
  src/main/java/org/example/onesteponestamp/javafx/AdminLogInController.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyAdminView.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListController.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListView.java
  src/main/resources/org/example/onesteponestamp/css/ImmigrationList.css
  src/main/resources/org/example/onesteponestamp/css/adminLogin.css
  src/main/resources/org/example/onesteponestamp/css/alert.css
  src/main/resources/org/example/onesteponestamp/css/autoApplyList.css
  src/main/resources/org/example/onesteponestamp/css/foreignerStyle.css
  src/main/resources/org/example/onesteponestamp/fxml/AutoApplyList.fxml
  src/main/resources/org/example/onesteponestamp/fxml/ImmigrationList.fxml
  src/main/resources/org/example/onesteponestamp/fxml/foreignerView.fxml
Labels: ⭐sytle

#67 더미데이터 생성기 완료
  src/main/resources/org/example/onesteponestamp/python/dummyBaker.py
Labels: 💫feature

#68 [JavaFx] 출입국 시스템 페이지 구현 및 스타일 적용
  src/main/java/org/example/onesteponestamp/javafx/ImmigrationForm.java
  src/main/java/org/example/onesteponestamp/javafx/ImmigrationFormController.java
  src/main/java/org/example/onesteponestamp/javafx/UserMainViewController.java
  src/main/resources/org/example/onesteponestamp/css/AutoApplyForm.css
  src/main/resources/org/example/onesteponestamp/css/ImmigrationForm.css
  src/main/resources/org/example/onesteponestamp/css/UserAutoApplyList.css
  src/main/resources/org/example/onesteponestamp/css/UserMain.css
  src/main/resources/org/example/onesteponestamp/fxml/AutoApplyFormView.fxml
  src/main/resources/org/example/onesteponestamp/fxml/ImmigrationFormView.fxml
  src/main/resources/org/example/onesteponestamp/fxml/UserAutoApplyListView.fxml
  src/main/resources/org/example/onesteponestamp/fxml/UserMainView.fxml
  src/main/resources/org/example/onesteponestamp/images/gate10.png
Labels: ⭐sytle, 🔮 refactor

#70 팝업 아이콘 변경하였습니다.
  src/main/java/org/example/onesteponestamp/javafx/ImmigrationFormController.java
  src/main/resources/org/example/onesteponestamp/images/error.png
Labels: ⭐sytle

#72 chore : css 수정
  src/main/resources/org/example/onesteponestamp/css/foreignerStyle.css
  src/main/resources/org/example/onesteponestamp/fxml/foreignerView.fxml
Labels: ✨chore, 💣 hotifx
