Repository SysWin1/OneStepOneStamp, pull requests merged in 2024-07, with the labels that each got.

#10 DB Connection Manager 생성 및 .idea 폴더 추적 해제
  .gitignore
  .idea/.name
  .idea/gradle.xml
  .idea/misc.xml
  .idea/uiDesigner.xml
  .idea/vcs.xml
  .idea/workspace.xml
  build.gradle
  src/main/java/module-info.java
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/common/DBConnectionManager.java
Labels: 💫feature, refactor, ✨chore

#11 자동 입출국 신청 (JAVA, ORACLE)
  src/main/java/org/example/onesteponestamp/DBConnect.java
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDAO.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyService.java
  src/main/java/org/example/onesteponestamp/autoapply/UUIDShortener.java
  src/main/java/org/example/onesteponestamp/common/Country.java
  src/main/java/org/example/onesteponestamp/common/DBConnectionManager.java
  src/main/java/org/example/onesteponestamp/common/VisaType.java
Labels: 💫feature

#15 외국인 조회/불법체류자 조회 기능 추가
  src/main/java/org/example/onesteponestamp/foreignvisitor/Foreigner.java
Labels: 💫feature

#17 Feature/16 immigration listpage
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationDAO.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationDTO.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationService.java
Labels: 💫feature, refactor

#19 [JavaFX] 자동입출국 신청서 form 생성(UI) 및 DB 연동
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDAO.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyService.java
  src/main/java/org/example/onesteponestamp/common/Country.java
  src/main/java/org/example/onesteponestamp/common/VisaType.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyForm.java
  src/main/java/org/example/onesteponestamp/javafx/SelectionMain.java
  src/main/java/org/example/onesteponestamp/javafx/UserMain.java
Labels: 💫feature, ⭐sytle, refactor, comment

#23 Feature/18 immigration java fx
  src/main/java/org/example/onesteponestamp/HelloController.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationDAO.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationService.java
  src/main/java/org/example/onesteponestamp/javafx/AdminMain.java
  src/main/java/org/example/onesteponestamp/javafx/EntryApplyForm.java
  src/main/java/org/example/onesteponestamp/javafx/SelectionMain.java
  src/main/java/org/example/onesteponestamp/javafx/UserMain.java
Labels: 💫feature, ⭐sytle

#25 21 [JavaFX] 사용자 자동 출입국 신청 결과 목록 반환
  src/main/java/module-info.java
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDAO.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDTO.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyService.java
  src/main/java/org/example/onesteponestamp/common/Country.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListView.java
  src/main/java/org/example/onesteponestamp/javafx/UserMain.java
Labels: 💫feature, refactor, ✨chore

#32 Feature/29 javafx foreigner list
  src/main/java/module-info.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationDAO.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationDTO.java
  src/main/java/org/example/onesteponestamp/immigration/ImmigrationService.java
  src/main/java/org/example/onesteponestamp/javafx/AdminMain.java
  src/main/java/org/example/onesteponestamp/javafx/EntryApplyForm.java
  src/main/java/org/example/onesteponestamp/javafx/ImmigrationListForm.java
  src/main/java/org/example/onesteponestamp/javafx/UserMain.java
Labels: 💫feature, refactor

#34 Feature/33 javafx style and service code refactor
  src/main/java/org/example/onesteponestamp/javafx/AdminMain.java
  src/main/java/org/example/onesteponestamp/javafx/EntryApplyForm.java
  src/main/java/org/example/onesteponestamp/javafx/UserMain.java
  src/main/resources/org/example/onesteponestamp/airplaneIcon.png
Labels: 💫feature, ⭐sytle

#37 [hotfix] 여권번호 제약조건 변경
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyForm.java
Labels: 💣hotifx

#39 외국인 DAO,DTO 분리 및 리팩토링
  src/main/java/org/example/onesteponestamp/foreigner/ForeignerDAO.java
  src/main/java/org/example/onesteponestamp/foreigner/ForeignerDTO.java
  src/main/java/org/example/onesteponestamp/foreignvisitor/Foreigner.java
Labels: refactor

#40 관리자 - "자동 출입국 신청서 결과" 목록 조회
  src/main/java/org/example/onesteponestamp/admin/LoginController.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApply.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDAO.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyService.java
  src/main/java/org/example/onesteponestamp/autoapply/UserAutoApplyDTO.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyForm.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyListView.java
Labels: 💫feature, refactor, rename

#41 [JavaFX] 외국인 Form 생성 및 리팩토링
  src/main/java/module-info.java
  src/main/java/org/example/onesteponestamp/javafx/AdminMain.java
  src/main/java/org/example/onesteponestamp/javafx/ForeignerForm.java
Labels: 💫feature, refactor

#46 42 [JavaFX] 관리자 - 자동 출입국 신청 목록 조회
  src/main/java/org/example/onesteponestamp/HelloApplication.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyAdminController.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyDAO.java
  src/main/java/org/example/onesteponestamp/autoapply/AutoApplyService.java
  src/main/java/org/example/onesteponestamp/javafx/AdminMain.java
  src/main/java/org/example/onesteponestamp/javafx/AutoApplyAdminView.java
Labels: 💫feature, ⭐sytle, 😶‍🌫️ rename
